aiaraldea.hauteskundeak2015.model.botoak2015 = [
  {
    "udalerria": "Amurrio",
    "urtea": 2015,
    "zinegotziak": 17,
    "errolda": 8199,
    "zenbatua": 0,
    "botoak": 5520,
    "baliogabeak": 137,
    "baliodunak": 0,
    "zuriak": 88,
    "hautagaitzei": 0,
    "abstentzioak": 2679,
    "EAJ-PNV": 2149,
    "EH Bildu": 1488,
    "PP": 282,
    "PSE-EE/PSOE": 364,
    "Guk Bai": 274,
    "Orain Amurrio": 738,
    hautatuak: {
      "EAJ-PNV": 7,
      "EH Bildu": 5,
      "PP": 1,
      "PSE-EE/PSOE": 1,
      "Guk Bai": 1,
      "Orain Amurrio": 2
    }
  },
  {
    "udalerria": "Artziniega",
    "urtea": 2015,
    "zinegotziak": 9,
    "errolda": 1416,
    "zenbatua": 0,
    "botoak": 0,
    "baliogabeak": 32,
    "baliodunak": 0,
    "zuriak": 23,
    "hautagaitzei": 0,
    "abstentzioak": 423,
    "EAJ-PNV": 384,
    "PP": 118,
    "PSE-EE/PSOE": 41,
    "EH Bildu": 395,
    "hautatuak": {
      "EAJ-PNV": 4,
      "PP": 1,
      "EH Bildu": 4
    }
  },
  {
    "udalerria": "Aiara",
    "urtea": 2015,
    "zinegotziak": 11,
    "errolda": 2266,
    "zenbatua": 0,	
    "botoak": 0,
    "baliogabeak": 21,
    "baliodunak": 0,
    "zuriak": 17,
    "hautagaitzei": 0,
    "abstentzioak": 633,
    "EAJ-PNV": 648,
    "PP": 85,
    "PSE-EE/PSOE": 46,
    "EH Bildu": 571,
    "Aiara Batuz": 245,
    "hautatuak": {
      "EAJ-PNV": 5,
      "PP": 0,
      "EH Bildu": 4,
      "Aiara Batuz": 2
    }
  },
  {
    "udalerria": "Laudio",
    "urtea": 2015,
    "zinegotziak": 17,
    "errolda": 15104,
    "zenbatua": 0,
    "botoak": 0,
    "baliogabeak": 142,
    "baliodunak": 0,
    "zuriak": 218,
    "hautagaitzei": 0,
    "abstentzioak": 5729,
    "EAJ-PNV": 2443,
    "PP": 579,
    "PSE-EE/PSOE": 1102,
    "EH Bildu": 2902,
    "Omnia": 1989,
    "hautatuak": {
      "EAJ-PNV": 5,
      "PP": 1,
      "PSE-EE/PSOE": 2,
      "EH Bildu": 5,
      "Omnia": 4
    }
  },
  {
    "udalerria": "Okondo",
    "zinegotziak": 9,
    "urtea": 2015,
    "errolda": 909,
    "zenbatua": 0,
    "botoak": 0,
    "baliogabeak": 23,
    "baliodunak": 0,
    "zuriak": 8,
    "hautagaitzei": 0,
    "abstentzioak": 156,
    "EAJ-PNV": 280,
    "PP": 1,
    "EH Bildu": 157,
    "Okondo Aurrera": 284,
    "hautatuak": {
      "EAJ-PNV": 3,
      "EH Bildu": 2,
      "Okondo Aurrera": 4
    }
  },
  {
    "udalerria": "Urduña",
    "urtea": 2015,
    "zinegotziak": 11,
    "errolda": 3355,
    "zenbatua": 0,
    "botoak": 0,
    "baliogabeak": 46,
    "baliodunak": 0,
    "zuriak": 32,
    "hautagaitzei": 0,
    "abstentzioak": 960,
    "EAJ-PNV": 844,
    "PP": 91,
    "PSE-EE/PSOE": 136,
    "URE-EEB": 145,
    "EH Bildu": 1101,
    "hautatuak": {
      "EAJ-PNV": 5,
      "PP": 0,
      "EH Bildu": 6
    }
  },
  {
    "udalerria": "Orozko",
    "urtea": 2015,
    "errolda": 1989,
    "zenbatua": 0,
    "zinegotziak": 11,
    "botoak": 0,
    "baliogabeak": 42,
    "baliodunak": 0,
    "zuriak": 15,
    "hautagaitzei": 0,
    "abstentzioak": 475,
    "EAJ-PNV": 385,
    "PP": 23,
    "PSE-EE/PSOE": 4,
    "EH Bildu": 267,
    "Adie": 778,
    "hautatuak": {
      "EAJ-PNV": 3,
      "EH Bildu": 2,
      "Adie": 6
    }
  },
  {
    "udalerria": "Arakaldo",
    "urtea": 2015,
    "zinegotziak": 5,
    "zenbatua": 0,
    "errolda": 116,
    "botoak": 0,
    "baliogabeak": 3,
    "baliodunak": 0,
    "zuriak": 5,
    "hautagaitzei": 0,
    "abstentzioak": 23,
    "EAJ-PNV": 36,
    "PP": 0,
    "EH Bildu": 43,
    "hautatuak": {
      "EAJ-PNV": 1,
      "EH Bildu": 4
    }
  },
  {
    "udalerria": "Arrankudiaga-Zollo",
    "urtea": 2015,
    "zinegotziak": 7,
    "errolda": 782,
    "zenbatua": 0,
    "botoak": 0,
    "baliogabeak": 8,
    "baliodunak": 0,
    "zuriak": 15,
    "hautagaitzei": 0,
    "abstentzioak": 138,
    "EAJ-PNV": 267,
    "PP": 6,
    "PSE-EE/PSOE": 6,
    "EH Bildu": 342,
    "hautatuak": {
      "EAJ-PNV": 3,
      "EH Bildu": 4
    }
  }
];
